[package]
name = "luac"
version = "0.1.0"
authors = ["周游 <mickey_zhouyou@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
